### ISSUE TITLE
Rewrite allo-todo to use stack layouts + update getting started guide accordingly

### ISSUE THREAD

**Issue by failuer** [alloverse/alloverse.github.io#3]
### Resolve the stack layouts
Either one of:
- [ ] Rewrite stacks so that they layout correctly even when two vertical stacks are nested
or
- [ ] Simplify the todo app so it only uses a single vertical stack

### Coding the Todo app
- [ ] Finish the stack-based layout instead of an absolute-positioned layout

### Update docs.alloverse.com > Getting started
- [ ] Add the new allo-todo snippets to the guide
- [ ] Update the explanatory text
- [ ] Update the screenshots (use the dev sandbox environment)

---

Original "parent" issue: https://github.com/alloverse/open-planning/issues/94

**Comment by failuer** [comment]
Blocked by not knowing how to best move forward with the LayoutStacks - nesting two vertical stacks causes them to not layout as expected.
